### ISSUE TITLE
Kickoff In time is wrong 

### ISSUE THREAD

**Issue by Lyonheart86** [zacs/ha-nfl#35]
The day of the week and time game starts is correct .. however on the card in the bottom left.. it says kick off in two days. IT should read 3.  I have this integration with three different cards. Only one of them is saying "3 Days" which is correct. Any advice on how to fix this please.

**Comment by zacs** [comment]
I am guessing this is by design because of the `kickoff_in` calculation -- it calculates human-understandable terms based on the relative time away. If you want the exact time of kickoff, you'd need to use the `date` field and parse it however you'd like. You could fork the card and make that change, but would need to do so out of the card repo here: https://github.com/D34DC3N73R/ha-nfl-card
